### ISSUE TITLE
Some documentation issues

### ISSUE THREAD

**Issue by bartbutenaers** [rikukissa/node-red-contrib-image-output#1]
Hi Riku,

Thanks for sharing this awesome contribution !!

## Installation command
You have following installation command in your readme file:
`npm install --save node-red-contrib-image-output`

However that fails because you have published your node on NPM as red-contrib-image-output (so without a previx 'node').  This means it has to be installed like this:
`npm install --save red-contrib-image-output`

You can see the different installation commands on your NPM page:

![image](https://user-images.githubusercontent.com/14224149/36101778-9b278e5a-100a-11e8-91dd-d63283ea33e5.png)

## Link from NPM to Github
Could you perhaps add a link from NPM to this Github page, by adding this stuff in your package.json file:

```
"bugs": {
        "url": "https://github.com/rikukissa/node-red-contrib-image-output/issues"
    },
    "homepage": "https://github.com/rikukissa/node-red-contrib-image-output",
    "repository": {
        "type": "git",
        "url": "https://github.com/rikukissa/node-red-contrib-msg-image-output"
    },
```

Then you get in the NPM page something similar to this:

![image](https://user-images.githubusercontent.com/14224149/36101584-114eb1fe-100a-11e8-8fed-1500f1374b76.png)

This makes it easier for users to create issues, or have a look at your code to learn from it.  Users like me :-)

## Keywords
Perhaps add some more keywords to your package.json file (like image, ...), so users can search for your node more easily.

## Missing image
On the readme page you show a nice image, that explains how the node can be used inside the Node-Red flow editor.  However that image is not visible on your NPM page:

![image](https://user-images.githubusercontent.com/14224149/36101845-c9860c90-100a-11e8-9167-92e52ef9a950.png)

I have also been struggling with this, and I solved it with the following steps.  Don't know if that is the best way to do it, but it works ...

+ I create a 'images' folder on my repository, where I upload my images:

    ![image](https://user-images.githubusercontent.com/14224149/36102062-62c4545c-100b-11e8-932f-e3c541d27221.png)

+ In the readme page I then insert the images like this:

    `![Startup](https://raw.githubusercontent.com/bartbutenaers/node-red-contrib-msg-speed/master/images/Startup.png)`

Thanks a lot,
Bart Butenaers

**Comment by rikukissa** [comment]
Heya, thanks a lot for your comments! 

I fixed the things you mentioned, but made a stupid mistake while publishing the package with a new name to npm, and now apparently have to wait for 24 hours before it can be republished. Gonna set a timer for myself to do it tomorrow :)

**Comment by rikukissa** [comment]
Now that I tried to reinstall (by `npm link`ing) the module with a new name, I get this error

```
[node-red-contrib-image-output/image-output] 'image-output' already registered by module red-contrib-image-output
```

I'm a bit worried whether changing the module name would break already existing flows. In that sense, it might make sense to just do what you suggested in the first place and fix the reference in README, although I'd prefer the module name to be prefixed with `node-red`..

**Comment by bartbutenaers** [comment]
Hmm, that is indeed a pitty...  
If I were you, I would also prefer to change it to node-...  
Perhaps you can change 'image-output' to something similar, and create your node-... module anyway.
There are only 50 people currently that have installed the old node.
If you add enough nice new stuff in your version 0.0.2, they will switch to your new node very quickly ;-)

Also I would add two more things:
- Add something to the info page of your node, because it is rather 'empty' currently:
    ![image](https://user-images.githubusercontent.com/14224149/36356347-15241792-14f1-11e8-89f3-2d562aab3f95.png)
- Once your version 0.0.2 is ready, I would open an _"[ANNOUNCE]node-red-contrib-image-output"_ discussion to the Node-Red forum.  A little advertisement for your node cannot harm ...

P.S. you have closed the issue about the buffers.  But beside the buffer issue, there were two other topics in that same issue (one about showing an error status on the node, and one about showing a default image when no images are available).  Would be great if you could still give your feedback, what you think about those enhancements !! I cannot reopen the issue ...

**Comment by rikukissa** [comment]
Good points.. Changing the node name would definitely do the trick and I like the idea of announcing the new features of this module once I've addressed the issues / enhancements you brought up. 
One thing I could also do is to add a post-install warning to the package with the old name, letting users know that all new versions are published with a new package name 

Reopened the issue, thanks for pointing that out :)

**Comment by rikukissa** [comment]
Alright, now there's a deprecation warning in place when you try to install this module with its own name + a new package https://www.npmjs.com/package/node-red-contrib-image-output where the node name is changed from `image-output` to `image`

![image](https://user-images.githubusercontent.com/1206987/36397658-9203f762-15bb-11e8-94d1-625c41241fcd.png)

- [ ] I think I still want to remove the node-red block from the old package's package.json, so it won't show on node-red's page anymore

**Comment by bartbutenaers** [comment]
That is a nice user friendly solution, I wasn't aware of.
And indeed if it doesn't appear anymore on flows.nodered.org, that would be better ...

**Comment by rikukissa** [comment]
Added a deprecation warning to 
https://www.npmjs.com/package/red-contrib-image-output and removed the node-red keyword.

Closing this for now
