### ISSUE TITLE
Adjustable image size

### ISSUE THREAD

**Issue by bartbutenaers** [rikukissa/node-red-contrib-image-output#2]
Hi Riku,

me again ;-)
Have tested your contribution, and I'm already a big fan ...

Currently the image width is fixed to '200':
`img.setAttribute('width', "200")`

As a result, the image preview is a little bit ***small*** in my flow editor, so I cannot see what is happening in the camera preview:

![image](https://user-images.githubusercontent.com/14224149/36103604-16c37a42-1010-11e8-9b59-79de66fe8525.png)

Could you please add an extra input field to the node's config screen, to make the width adjustable?  I mean something like this:

```
    <div class="form-row">
        <label for="node-input-width"><i class="fa fa-arrows-h"></i> Width</label>
        <input type="number" id="node-input-width">
    </div>
```

Which could then e.g. get your default of 200:

```
    defaults: {
       width:  {value:200, required:true, validate:RED.validators.number()},
       name: { value: "" }
    },
```

Thanks again !!!!
Bart Butenaers

**Comment by rikukissa** [comment]
I was actually also thinking about doing this, but decided to just go with MVP version of this node first. What do you think about having the images as resizable, in a way that you could just grab the corner of the image and start dragging to make it larger?

**Comment by bartbutenaers** [comment]
Hi Riku,

Nice to hear from you ;-)

Well that would be indeed much better.  When you have to change the width in the node's config screen, you have no idea how large it will be displayed in the flow.  As a result, you probably have to go N times to the config screen to get it right.

When you can grab it, you can draw it so it nicely fits into the existing flow.  So if you can manage that, it would be a great addition !!

Greetings from Belgium,
Bart

**Comment by rikukissa** [comment]
I'll see what I can do :)

**Comment by rikukissa** [comment]
I'll close this one now as well since there's a PR for this https://github.com/rikukissa/node-red-contrib-image-output/pull/6
