### ISSUE TITLE
How to I get this rendered image to be passed into telegram?

### ISSUE THREAD

**Issue by Yonny24** [rikukissa/node-red-contrib-image-output#28]
Hi. This is great for testing thanks.

Now I'm struggling, I thought the passthrough would send it as an image.
How do I get this rendered image to be sent to my telegram node?

![image](https://user-images.githubusercontent.com/64428686/143507744-2d04d9c9-5634-42c8-b177-92de34033a30.png)

Thanks

**Comment by dceejay** [comment]
For general questions it would be much better to ask on the general Node-RED discourse forum https://discourse.nodered.org/ - as this is much more a question about the telegram node (which I don't use) than the image node.
Closing here as this is not an issue with the code to fix.
