### ISSUE TITLE
Adjustable image heigth

### ISSUE THREAD

**Issue by bartbutenaers** [rikukissa/node-red-contrib-image-output#9]
Hi Riku (@rikukissa ),

Currently the width is defaulted to 200, and by your PR it is also adjustable.  As mentioned have (locally) a test version that allows to adjust the **width**, by dragging with the mouse.

Do you think it would also be useful to make the height adjustable by the user?  
Something like this:

![image](https://user-images.githubusercontent.com/14224149/36630746-ac2a43cc-196b-11e8-90c2-783ad61c42eb.png)

By default the checkbox would be selected, so the height field is invisible and your node works like it used to do until now: the height is automatically calculated.

When the checkbox is deactivated, the height can be specified.  Moreover in that case I could display some extra handles, to make sure the user can also change the height by using the mouse.

Two questions:

- Do you think this is useful or a complete waste of time?
- If useful, do you implement it or do I have to add it?  

For my mouse dragging, I will have to start from your PR ...
 
Thanks again !!
Bart

**Comment by rikukissa** [comment]
I'm almost inclined to say, we should have the aspect ratio locked by default and omit the Height field altogether. I'd imagine in most cases it's not really useful to be able to adjust width and height separately and by implementing this, we'd open the door for many new questions like if we should also allow selecting between stretching / cropping the image and in what way.

If I'd have to choose between this and being able to change the image size by dragging, I'd definitely go with the latter one.

**Comment by bartbutenaers** [comment]
Ok, that also makes sense.  So we don't add a height property on the config screen.  

But what about changing the image size by dragging:

- Do you only want to be able to change the **width** by dragging (so we also keep the aspect ratio fixed)
- Or do you want to be able to change both the **width and height** during dragging?  Because in this case we would also need a 'node.height' field under the cover, since the height need to be stored somewhere (to be able to restore it after a Node-Red restart).

**Comment by rikukissa** [comment]
I’d only go with width for now. Basically you could have the dragging handle on the right bottom corner of the image, which would at least give a small indication that it’ll resize it while still keeping the aspect ratio

**Comment by bartbutenaers** [comment]
Deal ...
